spin_manifest_version = 2

[application]
name = "http2"
version = "0.1.0"
authors = ["Kai Walter <kai.walter@outlook.de>"]
description = ""

[[trigger.http]]
route = "/..."
component = "http2"

[component.http2]
source = "target/wasm32-wasi/release/http2.wasm"
allowed_outbound_hosts = []
[component.http2.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
