spin_manifest_version = 2

[application]
name = "http1"
version = "0.1.0"
authors = ["Kai Walter <kai.walter@outlook.de>"]
description = ""

[[trigger.http]]
route = "/q-order-ingress"
component = "ingress"

[component.ingress]
source = "ingress/target/wasm32-wasi/release/ingress.wasm"
allowed_outbound_hosts = []
[component.ingress.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "ingress"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/health"
component = "health"

[component.health]
source = "health/target/wasm32-wasi/release/health.wasm"
allowed_outbound_hosts = []
[component.health.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "health"
watch = ["src/**/*.rs", "Cargo.toml"]
