apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributor
  template:
    metadata:
      labels:
        app: distributor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "distributor"
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
        dapr.io/enable-app-health-check: "true"
        dapr.io/log-level: "warn"
    spec:
      runtimeClassName: wasmtime-spin
      containers:
        - name: distributor
          image: { will be replace by deployment script }
          command: ["/"]
          env:
            - name: RUST_BACKTRACE
              value: "1"
          resources: # limit the resources to 128Mi of memory and 100m of CPU
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: .well-known/spin/health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: .well-known/spin/health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: distributor
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: distributor
